### ISSUE TITLE
Error running plugin

### ISSUE THREAD

**Issue by erwin16** [Maheshkumar-Kakade/mongoose-aggregate-paginate#14]
I am trying to use your plugin with aggregate ..
Running wo the plugin is fine , I get all the docs so the aggregate object is fine ...

options are  :  `OPTIONS: {"page":1,"limit":10}`

and I run it 

`  console.log('AGGREGATE: %j', aggregate);
    const options = { page: page, limit: limit };
    console.log('OPTIONS: %j', options);

    this.aggregatePaginate(aggregate, options, (err, results, pageCount, count) =>  {
      if(err) { console.err(err) }
      else { console.log(results) }
    })`

but I get an internal error 

`AGGREGATE: {"_pipeline":[{"$match":{}},{"$lookup":{"from":"groups","localField":"_group","foreignField":"_id","as":"group"}},{"$project":{"group":{"$let":{"vars":{"firstGroup":{"$arrayElemAt":["$group",0]}},"in":{"name":"$$firstGroup.name","description":"$$firstGroup.description"}}},"name":1,"description":1,"_id":0}}]}
OPTIONS: {"page":1,"limit":10}
      1) should allow superadmin to get all roles
`
Don't know if it's due to this bug.. but. 
line 1. of mongoose-aggregate-paginate you wrote 👍 
`'use scrict'`

should be 'use strict'

btw - mongoose-paginate uses Promises ... would it be a big deal to make mongoose-aggregate-paginate using Promises too ?

**Comment by Maheshkumar-Kakade** [comment]
can you please check now I have corrected typo _'use scrict'_ ?
It is not big deal to make mongoose-aggregate-paginate using Promises. I have planned do in July 2017.
Let me know if you still face same issue. If possible please send me dummy db and code.

**Comment by Maheshkumar-Kakade** [comment]
Promise support added
