### ISSUE TITLE
Paginate throws error when result returned are empty.

### ISSUE THREAD

**Issue by atanmayprdxn** [Maheshkumar-Kakade/mongoose-aggregate-paginate#24]
@Maheshkumar-Kakade 

The error:

error TypeError: Cannot read property 'count' of undefined
at /var/www/html/kiddoo-api/node_modules/mongoose-aggregate-paginate/lib/mongoose-aggregate-paginate.js:31:65

I will give a PR for this soon.

**Comment by Maheshkumar-Kakade** [comment]
@atanmayprdxn  Thank you for PR.
